// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe6McvwNdAyuS4Dw4lz8j-AD07-4bVRfs',
    appId: '1:803294915545:web:140a37be5a6d2273a507c8',
    messagingSenderId: '803294915545',
    projectId: 'harborlaptop',
    authDomain: 'harborlaptop.firebaseapp.com',
    storageBucket: 'harborlaptop.appspot.com',
    measurementId: 'G-1TML1PWYZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgcorbPTap457z0-0TaxlaZbVANo65YvA',
    appId: '1:803294915545:android:4f1c2bade22f2df4a507c8',
    messagingSenderId: '803294915545',
    projectId: 'harborlaptop',
    storageBucket: 'harborlaptop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAVyWe6HTC7gtEFdLgBfEp0q_WHzjGLhg',
    appId: '1:803294915545:ios:4549b3b7a40da9daa507c8',
    messagingSenderId: '803294915545',
    projectId: 'harborlaptop',
    storageBucket: 'harborlaptop.appspot.com',
    iosBundleId: 'com.example.laptopharbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAVyWe6HTC7gtEFdLgBfEp0q_WHzjGLhg',
    appId: '1:803294915545:ios:4549b3b7a40da9daa507c8',
    messagingSenderId: '803294915545',
    projectId: 'harborlaptop',
    storageBucket: 'harborlaptop.appspot.com',
    iosBundleId: 'com.example.laptopharbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe6McvwNdAyuS4Dw4lz8j-AD07-4bVRfs',
    appId: '1:803294915545:web:e46f23ff3cb88de9a507c8',
    messagingSenderId: '803294915545',
    projectId: 'harborlaptop',
    authDomain: 'harborlaptop.firebaseapp.com',
    storageBucket: 'harborlaptop.appspot.com',
    measurementId: 'G-E2TNJXZHK2',
  );
}
